name: Punchcard
description: 'Language support for DigitalGov Search - localizations, synonyms, stopwords, etc.'
license: null
openSourceProject: 1
governmentWideReuseProject: 0
tags:
    - GSA
    - DigitalGovSearch
    - language
contact:
    email: dawn.mccleskey@gsa.gov
