name: Punchcard
description: 'Language support for Search.gov - localizations, synonyms, stopwords, etc.'
license: 'https://creativecommons.org/publicdomain/zero/1.0'
openSourceProject: 1
governmentWideReuseProject: 0
tags:
    - GSA
    - Search.gov
    - language
contact:
    email: search@support.digitalgov.gov
