version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    docker:
       - image: cimg/ruby:2.6.7

    working_directory: ~/punchcard

    steps:
      - checkout

      - restore_cache:
          key: punchcard-{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: punchcard-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
